"""initial schema

Revision ID: 28696bace966
Revises: 
Create Date: 2026-05-14 08:54:54.917732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28696bace966'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', 'requester', 'auditor', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('created_ca', 'issued_cert', 'revoked_cert', 'approved_request', 'denied_request', 'login', 'logout', 'config_change', 'downloaded_cert', 'created_user', 'updated_user', 'generated_crl', 'renewed_cert', 'submitted_csr', name='auditaction'), nullable=False),
    sa.Column('resource_type', sa.Enum('ca', 'certificate', 'user', 'crl', name='auditresourcetype'), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_authorities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('root', 'intermediate', name='catype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', 'expired', 'revoked', name='castatus'), nullable=False),
    sa.Column('parent_ca_id', sa.String(length=36), nullable=True),
    sa.Column('private_key_encrypted', sa.Text(), nullable=False),
    sa.Column('certificate_pem', sa.Text(), nullable=False),
    sa.Column('key_algorithm', sa.Enum('RSA', 'EC', name='keyalgorithm'), nullable=False),
    sa.Column('key_size', sa.Integer(), nullable=False),
    sa.Column('subject_dn', sa.String(length=1024), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('not_before', sa.DateTime(), nullable=False),
    sa.Column('not_after', sa.DateTime(), nullable=False),
    sa.Column('max_path_length', sa.Integer(), nullable=True),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('crl_regen_interval_hours', sa.Integer(), nullable=False),
    sa.Column('ocsp_signing_mode', sa.Enum('ca_key', 'dedicated_cert', name='ocspsigningmode'), nullable=False),
    sa.Column('ocsp_signing_cert_pem', sa.Text(), nullable=True),
    sa.Column('ocsp_signing_key_encrypted', sa.Text(), nullable=True),
    sa.Column('crl_distribution_url', sa.String(length=512), nullable=True),
    sa.Column('ocsp_url', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_ca_id'], ['certificate_authorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_revocation_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ca_id', sa.String(length=36), nullable=False),
    sa.Column('crl_pem', sa.Text(), nullable=False),
    sa.Column('this_update', sa.DateTime(), nullable=False),
    sa.Column('next_update', sa.DateTime(), nullable=False),
    sa.Column('crl_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ca_id'], ['certificate_authorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ca_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'revoked', 'expired', 'denied', name='certificatestatus'), nullable=False),
    sa.Column('type', sa.Enum('server', 'client', 'custom', name='certificatetype'), nullable=False),
    sa.Column('private_key_encrypted', sa.Text(), nullable=True),
    sa.Column('certificate_pem', sa.Text(), nullable=True),
    sa.Column('csr_pem', sa.Text(), nullable=True),
    sa.Column('key_algorithm', sa.Enum('RSA', 'EC', name='keyalgorithm'), nullable=False),
    sa.Column('key_size', sa.Integer(), nullable=False),
    sa.Column('subject_dn', sa.String(length=1024), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('san', sa.JSON(), nullable=True),
    sa.Column('not_before', sa.DateTime(), nullable=True),
    sa.Column('not_after', sa.DateTime(), nullable=True),
    sa.Column('key_usage', sa.JSON(), nullable=True),
    sa.Column('extended_key_usage', sa.JSON(), nullable=True),
    sa.Column('custom_extensions', sa.JSON(), nullable=True),
    sa.Column('revocation_date', sa.DateTime(), nullable=True),
    sa.Column('revocation_reason', sa.Enum('key_compromise', 'ca_compromise', 'affiliation_changed', 'superseded', 'cessation_of_operation', 'certificate_hold', 'unspecified', name='revocationreason'), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ca_id'], ['certificate_authorities.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificates')
    op.drop_table('certificate_revocation_lists')
    op.drop_table('certificate_authorities')
    op.drop_table('audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
